Add Docker build and push to CI
DevelopingSpace/starchart pull request #210
Opened 2023-02-14 15:28 UTC by humphd

Fixes #200

This adds a new dependent job to CI, which will build a new Docker image and push it to the GitHub Container Registry.  The job will only run if we're doing a `push` to `main` (i.e., not for PRs).  It will also not run unless the rest of the CI jobs work.

2023-02-14 15:37 UTC, shawnyu5 submitted a review, later dismissed
Looks good!

2023-02-15 17:50 UTC, Genne23v requested changes

2023-02-15 19:32 UTC, humphd commented on .github/workflows/ci.yaml
> +    needs: [Build, Prettier, Unit-Tests, E2E-Tests, Dockerfile-Lint, ESLint, Type-Check]
No, this is great that you caught this, let me fix.

2023-02-15 19:39 UTC, shawnyu5 approved these changes

2023-02-15 19:42 UTC, Genne23v approved these changes

2023-02-15 20:29 UTC, merged