changed to check for type of group claim
DevelopingSpace/starchart pull request #356
Opened 2023-03-16 17:51 UTC by sfrunza13

Closes #352 

Groups claim is either an array or string so I check type of and either join or do not join to make sure that we use a string when creating user.

2023-03-16 17:58 UTC, humphd requested changes

2023-03-16 18:05 UTC, sfrunza13 commented on app/routes/login/callback.tsx
> +  if (typeof groups !== 'string') {
Oh, this is much nicer

2023-03-16 22:37 UTC, humphd approved these changes

2023-03-17 12:39 UTC, Eakam1007 approved these changes

2023-03-17 13:07 UTC, humphd commented
Let me know when this goes in and I'll update staging so people can test there.

2023-03-17 15:20 UTC, merged

2023-03-17 15:20 UTC, sfrunza13 commented
> Let me know when this goes in and I'll update staging so people can test there.

I merged it o7