Add integration for editing dns records
DevelopingSpace/starchart pull request #369
Opened 2023-03-17 15:54 UTC by Myrfion

## What it changes
- creates a new page by editing the DNS record (I changed the file name to match the new naming)
- updates the form component for DNS records so it supports editing 
- makes server-side integration with DNS records workflow and its API 

closes #331

2023-03-17 19:02 UTC, Eakam1007 commented
Seems like tests are failing due to the same error as the Type-Check error

2023-03-17 19:17 UTC, humphd commented
Can you rebase and update your code to use the new naming/layout that we landed in https://github.com/DevelopingSpace/starchart/pull/349?

2023-03-18 18:46 UTC, humphd requested changes
I tested this locally, and had to make the following changes:

```diff
diff --git a/app/routes/__index/domains/$dnsRecordId.tsx b/app/routes/__index/domains/$dnsRecordId.tsx
index bbf83d9..b6398cf 100644
--- a/app/routes/__index/domains/$dnsRecordId.tsx
+++ b/app/routes/__index/domains/$dnsRecordId.tsx
@@ -5,7 +5,7 @@ import { z } from 'zod';
 import { parseFormSafe } from 'zodix';
 import type { ActionArgs, LoaderArgs } from '@remix-run/node';
 import DnsRecordForm from '~/components/dns-record/form';
-import { updateDnsRequest } from '~/queues/dns/dns-flow.server';
+import { updateDnsRequest } from '~/queues/dns/update-record-flow.server';
 import { requireUser } from '~/session.server';
 import { getRecordById } from '~/models/record.server';

@@ -55,7 +55,7 @@ export const action = async ({ request }: ActionArgs) => {
     id: Number(data.id),
     username: user.username,
     type: data.type,
-    name: data.name,
+    subdomain: data.name,
     value: data.value,
   });
```

You should also rebase, since a lot has changed since you wrote this code.

2023-03-18 22:19 UTC, Myrfion commented
@humphd updated to new terminology and updated terminology inside of the table component itself, except the filename, because I am not sure if it is a good idea to do it in this PR (it would be a lot of changes)

2023-03-18 23:10 UTC, SerpentBytes commented on app/components/dns-record/dns-record-name.tsx
> +  basedomain: string;
I would use camelCase for `basedomain`.

2023-03-18 23:16 UTC, SerpentBytes commented on app/components/domains-table.tsx
>          <Tooltip label="Domain is live">
Should the `label` begin with "Domain..." or "Record..."

2023-03-18 23:18 UTC, SerpentBytes commented on app/components/domains-table.tsx
>                                  aria-label="Refresh domain"
typo in `aria-label`

2023-03-18 23:59 UTC, humphd requested changes
Looks really good.  A few things

2023-03-18 23:59 UTC, humphd commented on app/components/dns-record/form.tsx
> +  defaultDnsRecord?: Record;
What does `default` mean here? Can this not simply be `record` or `dnsRecord`?

2023-03-18 23:59 UTC, humphd commented on app/components/domains-table.tsx
>        title: 'Name was copied to clipboard',
`Subdomain was copied...`

2023-03-19 00:14 UTC, humphd requested changes
Can you also change the table heading `Name` to `Subdomain` as well on line 123 of `app/components/domains-table.tsx`

2023-03-19 00:25 UTC, humphd approved these changes

2023-03-19 00:28 UTC, humphd approved these changes

2023-03-19 00:36 UTC, SerpentBytes approved these changes

2023-03-19 00:39 UTC, merged