Don't fail on delete with missing record; update record status early
DevelopingSpace/starchart pull request #402
Opened 2023-03-21 20:25 UTC by humphd

Fixes #360
Fixes #390

This makes 2 changes to how the DNS logic works:

1. When we try to delete a record from Route53, we first check if the record is there.  If it is not, we are already done, and don't fail.  Doing this requires some changes to other parts of the code that expect a Change ID, which is now going to be `null`.  We simply skip doing the `insync` checks with Route53 and report back that the change is ready.
2. For all DNS flows, the database is updated first, so that the UI can poll for changes.

To test this:

1. Create a new domain, make sure the pending/active UI works
2. Update the domain, make sure the pending/active UI works
3. Delete the domain, make sure the pending/active UI works

2023-03-21 21:19 UTC, humphd commented
Rebased onto `main` with all the `DNS*` changes.  This is working locally for me.

2023-03-22 00:06 UTC, Genne23v requested changes
I was working on this issue as well. But this PR has a better solution. Thanks for this PR!

2023-03-22 00:06 UTC, Genne23v commented on app/queues/dns/update-dns-record-flow.server.ts
> +  await updateDnsRecordStatus(id, DnsRecordStatus.pending);
I think we should also update the DB after Route53 gets updated. I will write a PR for this one.

2023-03-22 14:12 UTC, humphd commented on app/lib/dns.server.ts
> +async function checkRecordExists(type: DnsRecordType, name: string, value: string) {
Good catch, fixing in new commit.

2023-03-22 14:33 UTC, humphd commented on app/models/dns-record.server.ts
> +export function updateDnsRecordStatus(id: DnsRecord['id'], status: DnsRecordStatus) {
Good idea, I made some improvements.

2023-03-22 14:34 UTC, humphd commented
I've made some updates, can you guys re-review?

2023-03-22 14:47 UTC, SerpentBytes commented on app/lib/dns.server.ts
> +    logger.warn('DNS Error in checkRecordExists', { name, type, value, error });
nit: `checkDnsRecordExists`

2023-03-22 14:51 UTC, SerpentBytes commented on app/lib/dns.server.ts
> +      logger.debug('DNS deleteRecord - no such record in Route53, skipping', { type, name, value });
typo: `deleteDnsRecord`

2023-03-22 14:53 UTC, SerpentBytes commented on app/lib/dns.server.ts
> +      logger.debug('DNS deleteRecord - no such record in Route53, skipping', { type, name, value });
Shouldn't this be `checkDnsRecordExists`?

2023-03-22 17:35 UTC, merged