Allow only alphanumerical and hyphen in record
DevelopingSpace/starchart pull request #480
Opened 2023-03-30 15:47 UTC by Genne23v

Close #437 

- Update regex to allow only alphanumeric characters and `-`
- Record name can't start or end with `-`
- Record name can't have consecutive `-` in the middle

2023-03-30 22:45 UTC, Eakam1007 approved these changes

2023-03-30 22:46 UTC, dadolhay reviewed
Why are we inhibiting users to start with `_` ? Providers requiring domain verification may very well require the use of it (just like Let's encrypt does)

2023-03-30 22:48 UTC, dadolhay requested changes
Looking at the ticket I don't think this is correct.

Let's encrypt does not allow _ ut the cert is going to be issued on the user's domain, so for that to be a problem the username would have to contain _.

I think we are solving a non-issue here

2023-03-31 16:54 UTC, dadolhay commented
@Genne23v @humphd 
Correct, I think is not needed, at least not the part that is limiting the use of _ characters

2023-03-31 16:56 UTC, humphd commented
Cool, let's take that bit out, and fix @Genne23v?

2023-03-31 17:37 UTC, Genne23v commented
> 

@humphd I think I can just close this PR. The change is limiting underscores in subdomain.

2023-03-31 17:38 UTC, humphd commented
Sounds good.

2023-03-31 17:56 UTC, closed without merging