Add error and catch boundaries
DevelopingSpace/starchart pull request #554
Opened 2023-04-10 01:09 UTC by Myrfion

- add a component for templating seen errors (the kind of you get in CatchBoundry) with default layout and error messages with possibility to customize error messages 
- add a component for unseen errors (the kind you get unexpectedly or when your `throw new Error`), it has some layout and accepts custom text as prop
- Put error and catch boundaries for both DNS records and certificate routes + root catch and error boundary 

![image](https://user-images.githubusercontent.com/32075241/230806188-31095755-dd63-4e4f-ab2c-d242f8152f50.png)

2023-04-10 01:49 UTC, Myrfion commented
Closes #391

2023-04-10 14:37 UTC, humphd requested changes

2023-04-10 14:37 UTC, humphd commented on app/routes/__index/certificate/index.tsx
> +      return 'Sorry we could not find you certificate key';
`'Sorry, your certificate is not issued yet. Please try again later.'`

2023-04-10 14:37 UTC, humphd commented on app/routes/__index/dns-records/$dnsRecordId.tsx
> +    throw new Response('Dns Record Id is not valid', {
`DNS Record ID is not valid`

2023-04-10 14:37 UTC, humphd commented on app/routes/__index/dns-records/index.tsx
> +      return 'Sorry we could not find your dns record';
DNS Record

2023-04-10 14:37 UTC, humphd commented on app/routes/__index/dns-records/index.tsx
> +      return 'We got an error processing requested action on your dns record';
DNS Record

2023-04-10 14:37 UTC, humphd commented on app/routes/__index/dns-records/index.tsx
> +    <UnseenErrorLayout errorText="We got an unexpected error working with your dns records, but don't worry our team is already on it's way to fix it" />
DNS Record.

Is our team already on its way to fixing this?  That seems hopeful, but also not true :)

2023-04-10 15:24 UTC, humphd commented
Let's confirm that the steps in https://github.com/DevelopingSpace/starchart/issues/445 are fixed by this (i.e., that we get back some useful error UI vs a crash stack).

2023-04-10 16:08 UTC, Eakam1007 commented
Looks like that error is being handled now:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/67077705/230942560-bfe691de-6576-4a41-b54c-29d35df7ee50.png">
I wonder if we want to capitalize record and id in the message though?

2023-04-10 16:19 UTC, Eakam1007 requested changes
A few small things, rest looks good to me

2023-04-10 16:19 UTC, Eakam1007 commented on app/routes/__index/certificate/index.tsx
> +      return 'Sorry we could not find you certificate';
```suggestion
      return 'Sorry we could not find your certificate';
```

2023-04-10 16:19 UTC, Eakam1007 commented on app/routes/__index/dns-records/index.tsx
> +      return 'We got an error processing requested action on your dns record';
Looks like this was missed

2023-04-11 00:17 UTC, humphd approved these changes

2023-04-11 01:51 UTC, Eakam1007 approved these changes

2023-04-11 11:46 UTC, merged