Add minimal footer
DevelopingSpace/starchart pull request #628
Opened 2023-04-17 14:26 UTC by SerpentBytes

## Description
Closes #605. In progress, not ready for review.

2023-04-20 15:48 UTC, SerpentBytes commented
The footer is a little buggy on some views and smaller screen resolutions. At the moment, I am adding `height` to be`100vh` on the container above the Footer, maybe that's the problem. I am looking into this.

2023-04-20 16:02 UTC, humphd commented
What I would do is use `<Flex>` to include the header, body, footer.  The header and footer will have fixed sizes, but the main part can use `flex="1"` to stretch to fill the whole space.  The `Flex` can have a `minHeight="100vh"` or `"100%` so it fills the entire viewport, and then use `flexDirection="column"` to have it spread things vertically.  This way, the main part of the page will use all the available space, and push the footer down to the bottom.

2023-04-20 16:56 UTC, SerpentBytes commented
@humphd let me know if I got it right.

2023-04-20 18:38 UTC, humphd requested changes

2023-04-20 18:38 UTC, humphd commented on app/routes/_auth.tsx
> +        <Container flex="1" maxW="container.xl" px={{ base: 4, md: 45 }} minHeight="100vh">
For `flex="1"` to work, you need to put it on a direct child of the `<Flex>` parent.  Can you eliminate `main`?  If not, use `<chakra.main flex="1">`

2023-04-21 15:56 UTC, humphd requested changes
I have to scroll down an inch or so to get the footer to show:

<img width="1234" alt="Screenshot 2023-04-21 at 11 50 04 AM" src="https://user-images.githubusercontent.com/427398/233680368-70908e21-41fd-47b7-8741-e746d447a474.png">
<img width="1234" alt="Screenshot 2023-04-21 at 11 50 11 AM" src="https://user-images.githubusercontent.com/427398/233680373-2a5bce87-ccfd-4c84-8fd6-b2d7af5b1a36.png">

It looks like it's roughly the hight of the header that's causing the issue.

I played with it locally, and this fixes it:

```diff
diff --git a/app/routes/_auth.tsx b/app/routes/_auth.tsx
index e59a8e7..4f219ab 100644
--- a/app/routes/_auth.tsx
+++ b/app/routes/_auth.tsx
@@ -7,9 +7,9 @@ import Footer from '~/components/footer';
 
 export default function Index() {
   return (
-    <Flex flexDir="column">
+    <Flex flexDir="column" h="100%">
       <Header />
-      <chakra.main flex="1" minHeight="100vh">
+      <chakra.main flex="1">
         <Container maxW="container.xl" px={{ base: 4, md: 45 }}>
           <Outlet />
         </Container>
```

2023-04-21 17:03 UTC, SerpentBytes commented
@humphd I have updated the code with your fix.

2023-04-21 18:11 UTC, humphd approved these changes

2023-04-21 19:47 UTC, sfrunza13 approved these changes

2023-04-21 19:48 UTC, merged