Issue 593
DevelopingSpace/starchart pull request #659
Opened 2023-04-21 15:14 UTC by Genne23v

Resolve #593 

Update the pending message to be clearer and add a button to navigate to home

2023-04-21 15:47 UTC, humphd requested changes

2023-04-21 15:47 UTC, humphd commented on app/routes/_auth.certificate._index.tsx
> +        desc="We have received your request, and will notify you by email when your certificate is ready. This process will take some time. You can move to another page while processing."
"...while we finish processing your request."

2023-04-21 19:33 UTC, humphd approved these changes

2023-04-22 00:42 UTC, Ririio approved these changes

2023-04-22 00:47 UTC, merged